// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/OMtlAKwmVTX
//  */
// import { CardHeader, CardContent, Card } from "@/components/ui/card"

// export function ListComponent() {
//   return (
//     <section className="w-full py-12">
//       <div className="container grid gap-6 md:gap-8 px-4 md:px-6 max-w-xl mx-auto lg:max-w-none">
//         <h1 className="text-2xl font-bold tracking-tight">Product Categories</h1>
//         <p className="text-gray-500 dark:text-gray-400">Browse our different categories.</p>
//         <div className="grid lg:grid-cols-3 gap-8">
//           <Card>
//             <img
//               alt="Category 1"
//               className="rounded-lg object-cover w-full aspect-[1/1] transition-opacity"
//               height="300"
//               src="/placeholder.svg"
//               width="300"
//             />
//             <CardHeader>
//               <h3 className="font-semibold">Category 1</h3>
//             </CardHeader>
//             <CardContent>
//               <p className="text-sm leading-none">Description for Category 1.</p>
//             </CardContent>
//           </Card>
//           <Card>
//             <img
//               alt="Category 2"
//               className="rounded-lg object-cover w-full aspect-[1/1] transition-opacity"
//               height="300"
//               src="/placeholder.svg"
//               width="300"
//             />
//             <CardHeader>
//               <h3 className="font-semibold">Category 2</h3>
//             </CardHeader>
//             <CardContent>
//               <p className="text-sm leading-none">Description for Category 2.</p>
//             </CardContent>
//           </Card>
//           <Card>
//             <img
//               alt="Category 3"
//               className="rounded-lg object-cover w-full aspect-[1/1] transition-opacity"
//               height="300"
//               src="/placeholder.svg"
//               width="300"
//             />
//             <CardHeader>
//               <h3 className="font-semibold">Category 3</h3>
//             </CardHeader>
//             <CardContent>
//               <p className="text-sm leading-none">Description for Category 3.</p>
//             </CardContent>
//           </Card>
//         </div>
//       </div>
//     </section>
//   )
// }
